--[[

Hello, and welcome to Seamless OOP Framework!


You can find both client and server environments beneath the following directories:

\ ServerScriptService : SERVER
\ StarterPlayer \ StarterPlayerScripts : CLIENT


Please note that the server library has had the unnecessary UI tweening capabilities removed.


Made with ❤️ by Vanguard & UncleTyrone!

--]]







--[[

SEAMLESS OOP FRAMEWORK
An OOP-oriented framework for Luau featuring seamless module handling and a custom library.

ABOUT:
- The Seamless OOP Framework is a project that was initially constructed by myself and co-developed with a UI developer/programmer named Vanguard written in PascalCase.
- This project with all of its components constructed was around 8,000 lines of code centered around being able to re-use, scale, and work with UI easily. What you will find here is the exact structure and basis of the framework while keeping all of its modules protected since the project was made under commission for a ROBLOX group. Excessive comments have been added for you to understand the concept of the project, and for other coders to make sense of.

FEATURES:
- The Seamless OOP Framework features modular component loading with threading, signal/connection management, a custom library for code reusability, and a completely modular format that can be applied to both Client and Server environments seamlessly. This system introduced smooth animations, responsive scaling, property-management for frames, and much more that allowed development to progress cleanly and easily. This framework was also built with type-casting and syntax in mind for the use of the programmers working with it.

DOCUMENTATION:
📖 Full API Documentation available from the github respository at (./API.md) - Complete reference guide with examples and usage patterns.

RESPONSIBILITIES:
- UncleTyrone (AKA myself) was responsible for the structure of the framework along with all of the feature-rich integrations such as threading, signal/connection management, and various useful library functions.
- Vanguard was responsible for filling in the framework's modules and making use of the framework to construct a seamless UI system. He also had several key input factors that helped design and construct the flow of the framework.

--]]